name: build-cv 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4
    - name: cv
      uses: dante-ev/latex-action@latest
      with:
        root_file: PELLOIN_Valentin_CV_en 
        working_directory: .
    - name: move
      run: mkdir -p github_artifacts && mv PELLOIN_Valentin_CV_en.pdf ./github_artifacts/
    - name: Upload pdf as artifact
      uses: actions/upload-artifact@v4
      with:
        name: PELLOIN_Valentin_CV_en.pdf
        path: ./github_artifacts
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
          enable_jekyll: true
  copy-index-to-build:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1.3
        env:
          key: main
          files: index.html CNAME
